eetfestijn/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^(?i)eetfestijn/admin/', include(admin.site.urls)),
    url(r'^(?i)eetfestijn/wiebetaaltwat/', include('wiebetaaltwat.urls')),
    url(r'^(?i)eetfestijn/', include('orders.urls')),
]

orders/urls.py
from django.conf.urls import url
from orders import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^summary/$', views.summary, name='summary'),
    url(r'^summary\.pdf$', views.summary_PDF, name='summary_PDF'),
    url(r'^overview/$', views.overview, name='overview'),
    url(r'^receipts/$', views.receipts, name='receipts'),
    url(r'^print/?$', views.print_script, name='print_script'),
]

orders/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import validate_comma_separated_integer_list

from wiebetaaltwat.models import Participant


class Item(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField(default=0)
    discounts = models.ManyToManyField('Discount', blank=True)
    description = models.CharField(max_length=200, blank=True)
    _printable_name = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name

    def discountstring(self):
        return ", ".join(map(str, self.discounts.all()))
    discountstring.short_description = 'Discounts'

    @property
    def printable_name(self):
        if self._printable_name:
            return self._printable_name
        return self.name

    def real_price(self, moment=None):
        discounts = [x for x in self.discounts.all() if x.is_active(moment)]
        price = self.price
        if not all(x.relative for x in discounts):
            price = min(x.value for x in discounts if not x.relative)
            price = min(price, self.price)
        return price - sum(x.value for x in discounts if x.relative)


class Order(models.Model):
    name = models.CharField(max_length=200)
    participant = models.ForeignKey(Participant, blank=True, null=True)
    paymentmethod = models.CharField(max_length=11,
                                     choices=(('participant', 'Participant'),
                                              ('bystander', 'Bystander'),
                                              ('outoflist', 'Out-of-list'),
                                              )
                                     )
    items = models.ManyToManyField(Item, through='ItemOrder')
    date = models.DateTimeField(default=timezone.now)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return self.name + ": " + ", ".join(map(str, self.items.all()))

    def itemstring(self):
        return ", ".join(map(str, self.items.all()))
    itemstring.short_description = 'Items'

    def total(self):
        return sum(x.real_price(self.date) for x in self.items.all())
    total.short_description = 'Total'

    @staticmethod
    def grandtotal():
        return sum(y.total() for y in Order.objects.all())


class ItemOrder(models.Model):
    item = models.ForeignKey(Item)
    order = models.ForeignKey(Order)

    def __str__(self):
        return str(self.item)


class Discount(models.Model):
    name = models.CharField(max_length=200)
    value = models.IntegerField(default=0)
    relative = models.BooleanField(default=False)
    days = models.CharField(max_length=20,
                            validators=[validate_comma_separated_integer_list])

    def __str__(self):
        return self.name

    def is_active(self, moment=None):
        if moment is None:
            moment = timezone.now()
        currentday = moment.weekday()
        return self.days and currentday in map(int, self.days.split(','))


class Category(models.Model):
    name = models.CharField(max_length=200)
    items = models.ManyToManyField(Item)
    random_item = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name


class Receipt(models.Model):
    contents = models.TextField()
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.contents

orders/views.py
from collections import Counter
import json
from six.moves import urllib
from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.conf import settings
from django.forms.models import model_to_dict
from django.db.models import Q
from django.utils.timezone import localtime

from orders.models import Item, Order, ItemOrder, Category, Receipt
from orders.templatetags.display_euro import euro
from wiebetaaltwat.models import Participant
from wiebetaaltwat.views import _create_wbw_session

import weasyprint
import dateutil.parser
from orders.utils import DateTimeEncoder


def index(request):
    if request.method == 'POST':
        error = False
        order = Order()
        order.paymentmethod = request.POST.get('paymentmethod')
        if order.paymentmethod in ['participant', 'bystander']:
            try:
                wbw_id = request.POST.get('participant', 'none')
                order.participant = Participant.objects.get(wbw_id=wbw_id)
                if order.paymentmethod == 'participant':
                    order.name = order.participant.name
            except:
                messages.error(request, "Je hebt niet aangegeven wie betaalt.")
                error = True
        if order.paymentmethod in ['outoflist', 'bystander']:
            try:
                order.name = request.POST.get('name')
                if not order.name:
                    raise ValueError("Name variable not defined.")
            except:
                messages.error(request, "Je hebt geen naam opgegeven.")
                error = True
        if not error:
            order.save()
            item_ids = request.POST.getlist('items[]')
            for item_id in item_ids:
                item = Item.objects.get(pk=item_id)
                ItemOrder.objects.create(item=item, order=order)
            messages.success(request, "Bestelling succesvol doorgegeven!")
            return HttpResponseRedirect(reverse('index'))
    categories = Category.objects.all().prefetch_related('items__discounts')
    total = Item.objects.count()
    n = 0
    cols = [[], []]
    for category in categories:
        cols[0 if n < total/2 else 1].append(category)
        n += category.items.count()
    context = {'cols': cols, 'participants': Participant.objects.all()}

    # add warning for eaters not in the wbw list
    context['warning_externals'] = settings.WARNING_EXTERNALS

    return render(request, 'orders/index.html', context)


def summary(request):
    c = Counter()
    for order in Order.objects.all():
        for item in order.items.all():
            c.update([item.printable_name])
    context = {'combined_order': sorted(dict(c).items())}
    return render(request, 'orders/summary.html', context)


def summary_PDF(request):
    html = summary(request).content
    response = HttpResponse(content_type="application/pdf")
    base_url = request.build_absolute_uri()
    weasyprint.HTML(string=html, base_url=base_url).write_pdf(response)
    return response


def print_script(request):
    return render(request, 'orders/printscript.html',
                  content_type='text/plain')


def receipts(request):
    receipts = Receipt.objects.order_by('-date')
    for receipt in receipts:
        receipt.dict = json.loads(receipt.contents)
        if receipt.dict['orders'] and 'date' in receipt.dict['orders'][0]:
            for order in receipt.dict['orders']:
                    order['date'] = dateutil.parser.parse(order['date'])
            receipt.latest = min(x['date'] for x in receipt.dict['orders'])
    return render(request, 'orders/receipts.html', {'receipts': receipts})


def overview(request):
    wbw_orders = (Order.objects.filter(paid=False)
                               .filter(Q(paymentmethod='participant') |
                                       Q(paymentmethod='bystander')))

    if request.method == 'POST':
        if 'process' in request.POST:
            orders = []
            for order in Order.objects.all():
                orderdict = model_to_dict(order)
                orderdict['items'] = [{'name': item.name,
                                       'price': item.real_price(order.date)}
                                      for item in order.items.all()]
                if order.participant:
                    orderdict['participant'] = order.participant.name
                orderdict['total'] = order.total()
                orders.append(orderdict)
            if orders:
                receipt = {'grandtotal': Order.grandtotal(),
                           'orders': orders}
                contents = json.dumps(receipt, cls=DateTimeEncoder)
                Receipt(contents=contents).save()
                Order.objects.all().delete()
            messages.success(request, "Alle bestellingen verwerkt!")
        elif 'remove' in request.POST:
            order = Order.objects.get(pk=request.POST['remove'])
            msg = "Bestelling van {.name} verwijderd!".format(order)
            order.delete()
            messages.success(request, msg)
        elif 'slack' in request.POST and hasattr(settings, 'SLACK'):
            jsondata = {'text': 'Nieuwe bestelling!',
                        'channel': settings.SLACK['channel'],
                        'username': settings.SLACK['username'],
                        'icon_emoji': settings.SLACK['icon_emoji']}
            for order in Order.objects.all():
                jsondata['text'] += '\n*{}* ({}):'.format(
                    order.name, euro(order.total()))
                items = [' {} ({})'.format(item.name,
                                           euro(item.real_price(order.date)))
                         for item in order.items.all()]
                jsondata['text'] += ', '.join(items)
            payload = {'payload': json.dumps(jsondata)}
            data = urllib.parse.urlencode(payload).encode('UTF-8')
            req = urllib.request.Request(settings.SLACK['webhook'], data)
            urllib.request.urlopen(req)
            messages.success(request, "Bestellingen gedeeld via Slack!")
        elif 'pay' in request.POST:
            try:
                wbw_id = request.POST.get('participant')
                session, response = _create_wbw_session()
                for order in wbw_orders:
                    date = datetime.strftime(localtime(order.date), "%Y-%m-%d")
                    desc = order.itemstring()
                    if order.paymentmethod == 'bystander':
                        desc += " (voor {})".format(order.name)
                    order.paid = True
                    payload = {'expense': {
                        'payed_by_id': wbw_id,
                        'name': desc,
                        'payed_on': date,
                        'amount': order.total(),
                        'shares_attributes': [
                            {
                                'member_id': order.participant.wbw_id,
                                'multiplier': 1,
                                'amount': order.total()
                            }
                        ]}}
                    url = ('https://api.wiebetaaltwat.nl/api/lists/{}/expenses'
                           .format(settings.WBW_LIST_ID))
                    response = session.post(url,
                                            json=payload,
                                            headers={'Accept-Version': '3'},
                                            cookies=response.cookies)
                    order.save()
            except:
                # This cannot happen accidentally
                HttpResponseRedirect(reverse('overview'))
        return HttpResponseRedirect(reverse('overview'))

    orders = Order.objects.all()
    context = {'orders': orders, 'grandtotal': Order.grandtotal(),
               'slack': hasattr(settings, 'SLACK'),
               'unpaid': wbw_orders.count() > 0,
               'participants': Participant.objects.all()}
    return render(request, 'orders/overview.html', context)

orders/templates/orders/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>eetFestijn</title>
    {% load bootstrap3 %}
    {% load display_euro %}
    {% bootstrap_css %}
    {% load staticfiles %}
    {% load git_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'orders/style.css' %}?v={% git_head %}" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4 sidebar">
                <h2>Bestelling</h2>
                <form role="form" method="post">
                    {% csrf_token %}
                    {% bootstrap_messages %}
                    <p>Hoe wil je betalen?</p>
                    <ul class="nav nav-pills wbw-preference">
                        <li class="active"><a class='paymentmethod' data-method='participant' data-toggle="pill" href="#" data-target="#participate-tab, #no-name-tab">- Ik sta op de wiebetaaltwat-lijst</a></li>
                        <li><a class='paymentmethod' data-method='bystander' data-toggle="pill" href="#" data-target="#participate-tab, #name-tab">- Ik betaal aan iemand die op de lijst staat</a></li>
                        <li><a class='paymentmethod' data-method='outoflist' data-toggle="pill" href="#" data-target="#no-participate-tab, #name-tab">- We regelen het buiten de lijst om</a></li>
                    </ul>
                    <input type='hidden' name='paymentmethod' value='participant' />
                    <hr>
                    <div class="tab-content">
                        <div id="name-tab" class="tab-pane">
                            <div class="form-group">
                                <label class="control-label" for="id_name">Naam</label>
                                <input class="form-control" id="id_name" maxlength="200" name="name" placeholder="Naam" title="" type="text"/>
                            </div>
                        </div>
                        <div id="no-name-tab" class="tab-pane"></div>
                    </div>
                    <div class="tab-content">
                        <div id="participate-tab" class="tab-pane active">
                            <div class="form-group">
                                <label class="control-label" for="id_participant">Lijst-deelnemer</label>
                                <select class="form-control" id="id_participant" name="participant">
                                    <option value="none" selected="selected">---------</option>
                                    {% for participant in participants %}
                                    <option value="{{ participant.wbw_id }}">{{ participant.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div id="no-participate-tab" class="tab-pane"></div>
                    </div>
                    {% if warning_externals %}
                    <div class="tab-content">
                        <div id="name-tab" class="tab-pane">
                            <div class="alert alert-warning">
                                <strong>Let op!</strong>
                                Als externe ben je van harte welkom om mee te eten, maar wij zijn geen thuisbezorgd.nl.
                                De regel is dan ook: <br /><br />
                                <strong>mee-eten = meefietsen</strong>

                                <br /><br />
                                Als jij degene bent die voor de externe betaalt, zorg er dan voor dat hij of zij
                                meefietst.
                            </div>
                        </div>
                        <div id="no-name-tab" class="tab-pane"></div>
                    </div>
                    {% endif %}
                    <hr>
                    <div class="form-group">
                        <label class="control-label">Voedsels</label>
                        <table class="table table-striped" id='ordertable'>
                            <tr><th style='width:70%'>Naam</th><th style='width:20%'>Prijs</th><th></th></tr>
                            <tr id='nofood'><td colspan='3'>Nog geen voedsels geselecteerd</td></tr>
                            <tr id='total' data-total='0'><th>Totaal: </th><td>{{ 0 | euro }}</td><td></td></tr>
                        </table>
                    </div>
                    <button type='submit' class='btn btn-primary' id='submitbtn'>Geef bestelling door</button>
                    <a class='btn btn-default' href="{% url 'summary' %}" data-toggle="tooltip" data-placement="top" title="Printvriendelijk overzicht">{% bootstrap_icon "print" %}</a>
                    <a class='btn btn-default' href="{% url 'summary_PDF' %}" data-toggle="tooltip" data-placement="top" title="Overzicht als PDF-document">{% bootstrap_icon "save" %}</a>
                    <a class='btn btn-default' href="{% url 'overview' %}" data-toggle="tooltip" data-placement="top" title="Uitgebreid overzicht">{% bootstrap_icon "list" %}</a>
                    <a class='btn btn-default' href="{% url 'receipts' %}" data-toggle="tooltip" data-placement="top" title="Bonnetjes">{% bootstrap_icon "tags" %}</a>
                </form>
            </div>
            <div class="col-sm-4 footer">
                <p><a href='https://github.com/joostrijneveld/eetfestijn/'>eetFestijn ({% git_head %})</a></p>
            </div>
            <div class="col-sm-8 col-sm-offset-4 main">
                <h2>Menu</h2>
            {% if cols.0 %}
                <div class='row'>
                    {% for col in cols %}
                    <div class="col-sm-6">
                        {% for category in col %}
                        <h3>{{ category.name }}</h3>
                        <table id="menu" class="table table-striped table-hover">
                            {% if category.random_item %}
                            <tr class='randomitem'>
                                <td>{{ category.random_item }}</td>
                                <td>{% bootstrap_icon "random" %}</td>
                            </tr>
                            {% endif %}
                            {% for item in category.items.all %}
                            <tr class='item' data-id='{{ item.pk }}' data-price='{{ item.real_price }}'>
                                <td>
                                    {{ item.name }}
                                    {% if item.description %}
                                        <span class='description' data-toggle="tooltip" data-placement="top" title="{{ item.description }}">{% bootstrap_icon "info-sign" %}</span>
                                    {% endif %}
                                    <span class='ordered'></span>
                                </td>
                                {% if item.real_price != item.price %}
                                <td>{{ item.real_price | euro }}<br><span class='oldprice'>{{ item.price | euro }}</span></td>
                                {% else %}
                                <td>{{ item.real_price | euro }}</td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </table>
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
            {% else %}
                <p>Geen menu beschikbaar.</p>
            {% endif %}
            </div>
        </div>
    </div>
    {% bootstrap_javascript jquery=1 %}
    <script type="text/javascript" src="{% static 'orders/script.js' %}?v={% git_head %}"></script>
    <div class='hidden' id='deleteicon'><a class='removelink text-danger'>{% bootstrap_icon "trash" %}</a></div>
    <div class='hidden' id='okicon'><span class='text-success'>{% bootstrap_icon "ok" %}</span></div>
</body>
</html>

orders/templates/orders/overview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>eetFestijn - overzicht</title>
    {% load bootstrap3 %}
    {% load display_euro %}
    {% load staticfiles %}
    {% load git_head %}
    {% load real_price_at %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'orders/overview.css' %}?v={% git_head %}" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-4 main">
                <h2>Bestellingen ({{ grandtotal | euro }})</h2>
                <form role='form' method='post' style='margin-bottom:25px;'>
                    {% csrf_token %}
                    <p>

                        Hieronder staan de bestellingen zoals ze nu zijn. Als je weer helemaal opnieuw
                        wilt beginnen met een lege lijst bestellingen, klik dan op
                        <button type="submit" name="process" value="all"
                                class="btn btn-success btn-xs"
                                onclick="return confirm('Weet je zeker dat je de bestellingen wilt verwerken?')">
                                alles verwerken {% bootstrap_icon 'tag' %}
                        </button>
                        om de lijst leeg te maken en een bonnetje te genereren.
                        {% if slack %}
                            Je kunt de huidige bestellingen ook delen via
                            <button type="submit" name="slack" value="post" class="btn btn-success btn-xs"
                                    onclick="return confirm('Weet je zeker dat je de bestellingen via Slack wilt delen?')">
                                    <i class="fa fa-slack"></i>
                                    Slack
                            </button>
                        {% endif %}
                        Zie ook het
                        <a class="btn btn-default btn-xs" role="button" href="{% url 'summary' %}">
                            {% bootstrap_icon 'print' %}
                            printvriendelijke overzicht
                        </a>.
                    </p>
                    <p>
                        Tip! Stuur de bestellingen door naar alle Péageprinters met deze handige bash-oneliner:<br>
                        <span style='font-size:12px;font-family:Menlo,Monaco,Consolas,"Courier New",monospace;'>{% include 'orders/printscript.html' %}</span>
                    </p>
                    <p>
                        Als je graag op het randje leeft kan dat ook met:<br>
                        <span style='font-size:12px;font-family:Menlo,Monaco,Consolas,"Courier New",monospace;'>curl https://joostrijneveld.nl/eetfestijn/print/ | sh</span>
                    </p>
                </form>
                {% bootstrap_messages %}
                {% if unpaid %}
                    <p><strong>Let op!</strong> Er zijn nog bestellingen die via wiebetaaltwat kunnen worden verwerkt. Wie heeft hiervoor betaald?</p>
                    <form role='form' method='post'>
                        {% csrf_token %}
                        <div class="form-group">
                            <div class='row'>
                                <div class='col-sm-8'>
                                    <select class="form-control" id="id_participant" name="participant">
                                        <option value="none" selected="selected">---------</option>
                                        {% for participant in participants %}
                                        <option value="{{ participant.wbw_id }}">{{ participant.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class='col-sm-3'>
                                    <button type="submit" name="pay"
                                            class="btn btn-warning"
                                            onclick="return confirm('Weet je zeker dat je alle wiebetaaltwat-betalingen als betaald wil markeren?')">
                                             {% bootstrap_icon 'euro' %} Alles betalen
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                {% endif %}
                {% for order in orders %}
                <form role='form' method='post'>
                    {% csrf_token %}
                    <table class="table" style='margin-bottom:25px;'>
                        <tr>
                            <th style='width:70%'>{{ order.name }}
                                <div class='ordertime'>{{ order.date | date:'Y-m-d H:i'}}</div>
                            </th>
                            <th>{{ order.total | euro }}</th>
                            <th><button name='remove' value='{{ order.pk }}' type='submit' class='btn btn-danger btn-xs' onclick="return confirm('Weet je zeker dat je deze bestelling van {{ order.name}} wilt verwijderen?')" {% if order.paid %}disabled{% endif %}>{% bootstrap_icon 'trash' %}</button></th>
                        </tr>
                        {% for item in order.items.all %}
                        <tr><td>{{ item.name }}</td><td>{{ item | real_price_at:order.date | euro }}</td><td></td></tr>
                        {% endfor %}
                        <tr>
                            <td colspan='3'>Betaalmethode:
                                {% if order.paid %}<s>{% endif %}
                                {% if order.paymentmethod == 'participant' %}
                                    <strong>Zelf</strong> via Wiebetaaltwat
                                {% elif order.paymentmethod == 'bystander' %}
                                    Via Wiebetaaltwat, via <strong>{{ order.participant.name }}</strong>
                                {% else %}
                                    <strong>Buiten de lijst om</strong>
                                {% endif %}
                                {% if order.paid %}</s> <em>Betaald!</em>{% endif %}
                            </td>
                        </tr>
                    </table>
                </form>
                {% endfor %}
            </div>
        </div>
        <div class="row">
           <div class="col-sm-4 col-sm-offset-4">
               <a href="{% url 'index' %}" role="button" class="btn btn-default btn-block"><span class="glyphicon glyphicon-chevron-left"></span>Ga terug naar de hoofdpagina</a>
            </div>
        </div>
    </div>
    {% bootstrap_javascript jquery=1 %}
</body>
</html>

orders/templates/orders/printscript.html
{% load absolute_reverse_url %}FNAME=`mktemp`; read -rp 'ru\sXXXXXXX?: ' UNAME && curl -sSo ${FNAME} {% absolute_reverse request 'summary_PDF' %} && smbclient -U ${UNAME} //payprint01.ru.nl/RU-Print -c "print ${FNAME}" && rm ${FNAME}

orders/templates/orders/receipts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>eetFestijn - bonnetjes</title>
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% load display_euro %}
    {% load staticfiles %}
    {% load git_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'orders/receipts.css' %}?v={% git_head %}" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-4 main">
                <h2>Bonnetjes</h2>
                {% if receipts %}
                <select class="form-control" id='receipts'>
                    {% for receipt in receipts %}
                        <option value="{{ receipt.pk }}">
                            {% if receipt.latest %}
                                {{ receipt.latest | date:'l, Y-m-d' }}
                            {% else %}
                                {{ receipt.date | date:'l, Y-m-d' }}
                            {% endif %}
                            ({{ receipt.dict.orders | length }} perso{{ receipt.dict.orders | pluralize:"on,nen" }},
                            {{ receipt.dict.grandtotal | euro }})
                        </option>
                    {% endfor %}
                </select>
                {% for receipt in receipts %}
                <div id='receipt{{ receipt.pk }}' class='receipt'>
                    <h5>verwerkt op {{ receipt.date | date:'l, Y-m-d' }}</h5>
                    {% if receipt.latest %}
                        <h5>laatste bestelling op {{ receipt.latest | date:'l, Y-m-d' }}</h5>
                    {% endif %}
                    <table class="table">
                    {% for order in receipt.dict.orders %}
                        <tr>
                            <th colspan='2'>
                                {{ order.name }}
                                <div class='ordertime'>
                                    {{ order.date | date:'Y-m-d H:i' }}
                                </div>
                            </th>
                        </tr>
                        {% for item in order.items %}
                            <tr><td>{{ item.name }}</td><td>{{ item.price | euro }}</td></tr>
                        {% endfor %}
                        {% if order.paymentmethod != 'outoflist' and order.paid %}
                            <tr><td class='total'>Betaald door:</td><td>{{ order.participant }}</td></tr>
                        {% endif %}
                        <tr><td class='total'>subtotaal:</td><td>{{ order.total | euro }}</td></tr>
                    {% endfor %}
                    <tfoot>
                        <tr><th class='total'>totaal:</th><td>{{ receipt.dict.grandtotal | euro }}</td></tr>
                    </tfoot>
                    </table>
                </div>
                {% endfor %}
                {% else %}
                <p>Er zijn nog geen bestellingen gedaan waar bonnetjes van zijn bewaard.</p>
                {% endif %}
            </div>
        </div>
        <div class="row">
           <div class="col-sm-4 col-sm-offset-4">
               <a href="{% url 'index' %}" role="button" class="btn btn-default btn-block">
                   {% bootstrap_icon 'chevron-left' %}
                   Ga terug naar de hoofdpagina
               </a>
            </div>
        </div>
    </div>
    {% bootstrap_javascript jquery=1 %}
    <script type="text/javascript" src="{% static 'orders/receipts.js' %}?v={% git_head %}"></script>
</body>
</html>